const ENV = {
  L1_RPC_QUICKNODE_URL: import.meta.env.VITE_NETWORK_L1_RPC_QUICKNODE_URL,
  L1_CHAIN_NAME: import.meta.env.VITE_NETWORK_L1_CHAIN_NAME,
  L1_CHAIN_ID: +import.meta.env.VITE_NETWORK_L1_CHAIN_ID,

  L2_RPC_QUICKNODE_URL: import.meta.env.VITE_NETWORK_L2_RPC_QUICKNODE_URL,
  L2_CHAIN_NAME: import.meta.env.VITE_NETWORK_L2_CHAIN_NAME,
  L2_CHAIN_ID: +import.meta.env.VITE_NETWORK_L2_CHAIN_ID,

  L1_BLOCK_EXPLORER_URL: import.meta.env.VITE_NETWORK_L1_BLOCK_EXPLORER_URL,
  L1_BLOCK_EXPLORER_NAME: import.meta.env.VITE_NETWORK_L1_BLOCK_EXPLORER_NAME,
  L1_BLOCK_EXPLORER_API: import.meta.env.VITE_NETWORK_L1_BLOCK_EXPLORER_API,

  L2_BLOCK_EXPLORER_URL: import.meta.env.VITE_NETWORK_L2_BLOCK_EXPLORER_URL,
  L2_BLOCK_EXPLORER_NAME: import.meta.env.VITE_NETWORK_L2_BLOCK_EXPLORER_NAME,
  L2_BLOCK_EXPLORER_API: import.meta.env.VITE_NETWORK_L2_BLOCK_EXPLORER_API,

  L1_NATIVE_CURRENCY_SYMBOL: import.meta.env
    .VITE_NETWORK_L1_NATIVE_CURRENCY_SYMBOL,
  L1_NATIVE_CURRENCY_NAME: import.meta.env.VITE_NETWORK_L1_NATIVE_CURRENCY_NAME,
  L1_NATIVE_CURRENCY_DECIMALS: +import.meta.env
    .VITE_NETWORK_L1_NATIVE_CURRENCY_DECIMALS,

  L2_NATIVE_CURRENCY_SYMBOL: import.meta.env
    .VITE_NETWORK_L2_NATIVE_CURRENCY_SYMBOL,
  L2_NATIVE_CURRENCY_NAME: import.meta.env.VITE_NETWORK_L2_NATIVE_CURRENCY_NAME,
  L2_NATIVE_CURRENCY_DECIMALS: +import.meta.env
    .VITE_NETWORK_L2_NATIVE_CURRENCY_DECIMALS,

  L1_ENS_REGISTRY_ADDRESS: import.meta.env
    .VITE_CONTRACT_L1_ENS_REGISTRY_ADDRESS,
  L1_ENS_UNIVERSAL_RESOLVER_ADDRESS: import.meta.env
    .VITE_CONTRACT_L1_ENS_UNIVERSAL_RESOLVER_ADDRESS,
  L1_ENS_UNIVERSAL_RESOLVER_BLOCK_CREATED: import.meta.env
    .VITE_CONTRACT_L1_ENS_UNIVERSAL_RESOLVER_BLOCK_CREATED,
  L1_MULTI_CALL3_ADDRESS: import.meta.env.VITE_CONTRACT_L1_MULTI_CALL3_ADDRESS,
  L1_MULTI_CALL3_BLOCK_CREATED: import.meta.env
    .VITE_CONTRACT_L1_MULTI_CALL3_BLOCK_CREATED,

  L2_MULTI_CALL3_ADDRESS: import.meta.env.VITE_CONTRACT_L2_MULTI_CALL3_ADDRESS,
  L2_MULTI_CALL3_BLOCK_CREATED: import.meta.env
    .VITE_CONTRACT_L2_MULTI_CALL3_BLOCK_CREATED,

  L2OUTPUT_ORACLE_PROXY_ADDRESS: import.meta.env
    .VITE_CONTRACT_L2OUTPUT_ORACLE_PROXY_ADDRESS,
  PORTAL_PROXY_ADDRESS: import.meta.env.VITE_CONTRACT_PORTAL_PROXY_ADDRESS,
  L1STANDARD_BRIDGE_PROXY_ADDRESS: import.meta.env
    .VITE_CONTRACT_L1STANDARD_BRIDGE_PROXY_ADDRESS,
  L1CROSS_DOMAIN_MESSENGER: import.meta.env
    .VITE_CONTRACT_L1CROSS_DOMAIN_MESSENGER,
  L1ERC721_BRIDGE_ADDRESS: import.meta.env
    .VITE_CONTRACT_L1ERC721_BRIDGE_ADDRESS,
  L2L1_MESSAGE_PASSER_ADDRESS: import.meta.env
    .VITE_CONTRACT_L2L1_MESSAGE_PASSER_ADDRESS,
  L2STANDARD_BRIDGE_PROXY_ADDRESS: import.meta.env
    .VITE_CONTRACT_L2STANDARD_BRIDGE_PROXY_ADDRESS,

  DISPUTE_GAME_FACTORY_PROXY: import.meta.env
    .VITE_CONTRACT_DISPUTE_GAME_FACTORY_PROXY_ADDRESS,
};

export default ENV;
